export default[
  {
      bio : "\"Rapper and poet whose career took off when she was featured on Chance the Rapper's 2013 song \"\"Lost.\"\" Her first mixtape as a solo artist Telefone was released to positive reviews in 2016.\"\r\n",
      contact : "inquiry@nbsmgmt.com",
      facebook : "https://www.facebook.com/nonameraps/",
      instagram : "https://www.instagram.com/nonamehiding/",
      music : "https://firebasestorage.googleapis.com/v0/b/crescendo-music2.appspot.com/o/Noname%20-%2008.%20Forever%20(ft%20%20Ravyn%20Lenae%20%20Joseph%20Chilliams)-%5BAudioTrimmer.com%5D.mp3?alt=media&token=67f5ab3a-62a6-4446-bd57-d73b1034347d",
      name : "Noname",
      next_show : "https://chicago.ohmyrockness.com/search?q=noname",
      pics : ["https://www.rollingstone.com/wp-content/uploads/2018/09/180803_RollingStone_noname0257_3.jpg"],
      soundcloud : "https://soundcloud.com/noname",
      spotify : "https://open.spotify.com/artist/1EpyA68dKpjf7jXmQL88Hy?si=8DJzoJoZTZKYofs9MJ8PAA",
      tags : "hip-hop; chill rap; conscious rap",
      twitter : "https://twitter.com/noname?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"
    },
    {
      bio : "\"L.A. VanGogh is a multi-faceted multi-genre performer producer and songwriter with a unique sound inspired by hip-hop jazz r&b and dream pop.\"\r\n",
      contact : "L.A.VanGoghMGMT@gmail.com",
      facebook : "https://www.facebook.com/lavangoghmusic/",
      instagram : "https://www.instagram.com/lavangogh/",
      music : "https://firebasestorage.googleapis.com/v0/b/crescendo-music2.appspot.com/o/L.A.%20VanGogh%20-%20Be%20Careful-%5BAudioTrimmer.com%5D.mp3?alt=media&token=415ce945-791f-4cfb-8cd4-92e46a8360ab",
      name : "L.A. VanGogh",
      next_show : "N/A",
      pics : ["https://media1.fdncms.com/chicago/imager/u/original/65088834/la-vangogh-1.jpg"],
      soundcloud : "https://soundcloud.com/lavangogh",
      spotify : "https://open.spotify.com/artist/5QXfvuEYlxFQcYFImEG4rl?si=x0kJSbMhSyyexRjK60aECQ",
      tags : "hip-hop; chill rap; conscious rap",
      twitter : "https://twitter.com/LAVanGogh"
    },
    {
      bio : "\"\"\"The voice of Chicago artist Ness Heads has a soft malleability. Sometimes it's almost as if she's singing and rapping at the same time inhabiting space between the two. And while she hasn't exhibited wide range as a singer she's not here for that; she's here to construct a vibe.\"\" -Tara Mahadevan\"\r\n",
      contact : "eddie@abstract-mgmt.com",
      facebook : "https://www.facebook.com/NessHeads/",
      instagram : "https://www.instagram.com/nessheads/",
      music : "https://firebasestorage.googleapis.com/v0/b/crescendo-music2.appspot.com/o/Freakshow(1)-%5BAudioTrimmer.com%5D.mp3?alt=media&token=c6913c81-bdf4-4345-b93d-490bcc47345f",
      name : "Ness Heads",
      next_show : "N/A",
      pics : ["https://static1.squarespace.com/static/55664553e4b0e48846329dc0/t/5bb635b4b208fc90b113ce11/1538667982255/Image+from+iOS.jpg"],
      soundcloud : "https://soundcloud.com/nessheads",
      spotify : "https://open.spotify.com/artist/6fS4Lmzu6U2g6mrf93Vs4w?si=z3vuN2dfQiKAzBa_RwNvaQ",
      tags : "hip-hop; pop",
      twitter : "https://twitter.com/Nessheads"
    },
    {
      bio : "\"Chai Tulani was born in Nakuru Kenya and raised in Chicago IL. Though Tulani moved to the states at only four years old his culture remains one of the main ingredients of his music. Known for his raspy but soulful voice Tulani creates a wide variety of music merging genres like reggae soul Afro beat and hip-hop.\"\r\n",
      contact : "chaitulanimanagment@gmail.com ",
      facebook : "https://www.facebook.com/ChaiTulani/",
      instagram : "https://www.instagram.com/chaitulani/",
      music : "https://firebasestorage.googleapis.com/v0/b/crescendo-music2.appspot.com/o/Chai%20Tulani%20-%20All%20the%20Way%20(ft.%20Christian%20JaLon%20%26%20Aliforthego)-%5BAudioTrimmer.com%5D.mp3?alt=media&token=9b3a6c24-26ed-4b09-9a59-4435e7981249",
      name : "Chai Tulani",
      next_show : "N/A",
      pics : ["http://www.lh-st.com/assets/root/images/artist/lhst/1125_ChaiTulaniSITE.jpg"],
      soundcloud : "https://soundcloud.com/chaitulani",
      spotify : "https://open.spotify.com/artist/0keSE8mg7VKDjjpFIvUYan?si=b5hLfojWRROzhQstoN0_5Q",
      tags : "Afrobeat; hip-hop; pop",
      twitter : "https://twitter.com/ChaiTulani"
    },
    {
      bio : "\"I'm CJ Run (they/them). Rapper-singer born in Germany raised in the UK based in Champaign/Chicago IL. I write about what I feel and I hope you feel it too. Enjoy your stay :) \"\r\n",
      contact : "seth@nicodemusagency.com",
      facebook : "https://www.facebook.com/CJRunMusic/",
      instagram : "https://www.instagram.com/cj.run/",
      music : "https://firebasestorage.googleapis.com/v0/b/crescendo-music2.appspot.com/o/CJ%20Run%20-%20Mercury-%5BAudioTrimmer.com%5D.mp3?alt=media&token=24a06449-c010-4fdc-ad83-5b95db60a14a",
      name : "CJ Run",
      next_show : "N/A",
      pics : ["https://www.pinknews.co.uk/images/2018/08/Five-up-and-coming-artists.00_00_06_01.Still007-650x366.jpg"],
      soundcloud : "https://soundcloud.com/cjeighrun",
      spotify : "https://open.spotify.com/artist/17g2kHe1KbJjcO3VUDSwVl?si=YYyqB9IvTeKLVlupTouSoQ",
      tags : "hip-hop; electronic; alternative",
      twitter : "https://twitter.com/itscjrun"
    },
    {
      bio : "\"Iris Temple provides a refreshing head space with every chorus every song. A tender adventure of sorrow and joy. The Chicago duo (by way of Kansas City) started making music together in high school and have steadily picked up speed and notoriety over the years. The two early twent-somethings (made up of Quinn Barlow on vocals/artwork and Quinn Cochrain on vocals/production) have fine-tuned their eclectic sound and grown deeply in their craft. Focusing on strong songwriting organic production and sharp instrumentation the group properly blends a medley of genres that they call home. From soul to hip-hop to R&B to folk and beyond it's in inimitable signature style.\"\r\n",
      contact : "iristemplemusic@gmail.com",
      facebook : "https://www.facebook.com/iristemplemusic/",
      instagram : "https://www.instagram.com/iristemplemusic/",
      music : "https://firebasestorage.googleapis.com/v0/b/crescendo-music2.appspot.com/o/Iris%20Temple%20-%20Theatre%20(Official%20Audio)-%5BAudioTrimmer.com%5D.mp3?alt=media&token=7c1f88a0-b154-4cd2-8c98-f1b4e015d71e",
      name : "Iris Temple",
      next_show : "N/A",
      pics : ["static1.squarespace.com/static/53bad273e4b04332c190511a/564a78b0e4b0776f9c0da5fc/5ac1ae19aa4a998a3b9f3055/1522643071306/Iris+Temple+music.jpg"],
      soundcloud : "https://soundcloud.com/iristemple",
      spotify : "https://open.spotify.com/artist/1ti0u37FfK0AO8cM2n7Ncr?si=e6KaUOkcSCmc1XxiGo_AZw",
      tags : "soul; neo-soul; hip-hop",
      twitter : "https://twitter.com/iristemplemusic"
    },
    {
      bio : "\"Originally from St. Louis she's released demos and loose singles throughout the years (as well as her Phases EP back in 2017) but her current focus is stronger than ever. Her newest offering Moonflower is a four song testament of rebirth that showcases her abilities both instrumentally and vocally. With reflective narratives of doubt reassurances and visible growth the songstress crafts tracks that fit nicely next to a late night candle burning a long cruise down a quiet road a meditative afternoon with close friends. This is closure and self love in musical form. Loona Dae's sound is ambient and cosmic. It's a bright light when the world is shrouded in darkness.\"\r\n",
      contact : "loonadaemusic@gmail.com",
      facebook : "https://www.facebook.com/LoonaDae/",
      instagram : "https://www.instagram.com/loonadae/",
      music : "https://firebasestorage.googleapis.com/v0/b/crescendo-music2.appspot.com/o/Loona%20Dae%20-%20Summertime%20(U%20Remind%20Me)-%5BAudioTrimmer.com%5D.mp3?alt=media&token=e94efb95-1276-4040-ba1c-433bc71367bd",
      name : "Loona Dae",
      next_show : "N/A",
      pics : ["http://chicago.thedelimagazine.com/sites/upload-files/50472016_1684975111603776_2558137668877680640_o.jpg"],
      soundcloud : "https://soundcloud.com/loonadae",
      spotify : "https://open.spotify.com/artist/0GEOpkT89APucSXvhPvymq?si=XTnLH3_mSs6_TvMjInPPnQ",
      tags : "soul; neo-soul",
      twitter : "https://twitter.com/Loonadae"
    },
    {
      bio : "\"A soft savory voice that's sharp enough to remind you of what happens when you get too close to the sun\"\r\n",
      contact : "kainamgmt@gmail.com",
      facebook : "https://www.facebook.com/kainamusic/",
      instagram : "https://www.instagram.com/kaina/",
      music : "https://firebasestorage.googleapis.com/v0/b/crescendo-music2.appspot.com/o/KAINA%20-%20cry-%5BAudioTrimmer.com%5D.mp3?alt=media&token=5628fddb-c487-4721-bc3c-a8b03fa4b56a",
      name : "KAINA",
      next_show : "N/A",
      pics : ["https://media2.fdncms.com/chicago/imager/u/mobilestory/25248785/gw-kaina-900.jpg"],
      soundcloud : "https://soundcloud.com/kainamusic",
      spotify : "https://open.spotify.com/artist/7c6eQSFEfIt9rV3gh4cgtj?si=iuhWSxW9ToCu3g45TIIuqw",
      tags : "soul; neo-soul; indie; alternative",
      twitter : "https://twitter.com/kainacastillo"
    },
    {
      bio : "\"Singer songwriter and producer Tatiana Hazel creates eclectic non-traditional pop ballads which distinguish her as an Indie Pop artist. Tatiana Hazel grew up in the Logan Square neighborhood of Chicago with parents and siblings whose musical tastes spanned hip-hop metal and duranguense. Hazel sights her personal influences as pop stars such as Madonna Selena and Lady Gaga.\"\r\n",
      contact : "tatianahazel@gmail.com",
      facebook : "https://www.facebook.com/TatianaHazelMusic/",
      instagram : "",
      music : "https://firebasestorage.googleapis.com/v0/b/crescendo-music2.appspot.com/o/Knew%20You%20Would-%5BAudioTrimmer.com%5D.mp3?alt=media&token=1221460e-18f6-4bbe-9622-22dcb7bda50d",
      name : "Tatiana Hazel",
      next_show : "N/A",
      pics : ["https://static1.squarespace.com/static/572acd717c65e426e2b580d9/t/5b5b877aaa4a993fa3ba3014/1532725124170/Tatiana3.jpg"],
      soundcloud : "https://soundcloud.com/tatianahazel",
      spotify : "https://open.spotify.com/artist/5NvrRBcK6hRuboOL0CtZXU?si=5-N9qimVRSWm41UcP0oKwg",
      tags : "pop; en español; alternative",
      twitter : "https://twitter.com/TatianaHazel"
    },
];